# Generated by Django 5.2.16 on 2026-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='target_branches',
            field=models.CharField(default='ALL', help_text='Target branches for job posting (e.g. CO,IT,AIML or ALL)', max_length=255),
        ),
    ]
