# Generated by Django 6.0.7 on 2026-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_certification_notification_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
