# Generated by Django 6.0.7 on 2026-08-05 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(default='Candidate', max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('target_role', models.CharField(max_length=100)),
                ('experience_level', models.CharField(default='Entry Level', max_length=50)),
                ('total_questions', models.IntegerField(default=5)),
                ('current_question_index', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('overall_score', models.IntegerField(default=0)),
                ('domain_score', models.IntegerField(default=0)),
                ('speech_score', models.IntegerField(default=0)),
                ('body_language_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('avg_eye_contact', models.FloatField(default=0.0)),
                ('avg_posture_score', models.FloatField(default=0.0)),
                ('avg_fidget_score', models.FloatField(default=0.0)),
                ('avg_smile_score', models.FloatField(default=0.0)),
                ('key_strengths', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('summary_verdict', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(default='technical', max_length=50)),
                ('question_text', models.TextField()),
                ('candidate_response', models.TextField(blank=True, default='')),
                ('eye_contact_pct', models.FloatField(default=0.0)),
                ('posture_score', models.FloatField(default=0.0)),
                ('fidget_level', models.FloatField(default=0.0)),
                ('smile_level', models.FloatField(default=0.0)),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('suggested_model_answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_items', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
    ]
